New changes made
jishnukoottala/react-wtih-redux-toolkit pull request #1
Opened 2023-07-13 05:04 UTC by braincodeishan

Kindly review and merge

2023-07-13 13:45 UTC, jishnukoottala requested changes
please do all these changes

2023-07-13 13:45 UTC, jishnukoottala commented on src/components/ProductDetail.jsx
> +            dsghajdghsgh
remove this "dsghajdghsgh"

2023-07-13 13:45 UTC, jishnukoottala commented on src/components/ProductDetail.jsx
> +  console.log("product data",productData);
remove console log

2023-07-13 13:45 UTC, jishnukoottala commented on src/store/products/productsSlice.js
> +        console.log("HIT ONCE and called api");
remove console log

2023-07-13 13:45 UTC, jishnukoottala commented on src/store/products/productsSlice.js
> +console.log(productsApi);
remove console log

2023-07-13 13:45 UTC, jishnukoottala commented on src/components/Product.jsx
> +          <Text weight={500}>{title.length>30?title.substring(0,29)+"...":title}</Text>
set width/height of this text box, and and overflow: ellipsis

2023-07-14 05:12 UTC, braincodeishan commented on src/components/ProductDetail.jsx
> +  console.log("product data",productData);
done

2023-07-14 05:12 UTC, braincodeishan commented on src/store/products/productsSlice.js
> +        console.log("HIT ONCE and called api");
done

2023-07-14 05:12 UTC, braincodeishan commented on src/store/products/productsSlice.js
> +console.log(productsApi);
done

2023-07-14 05:18 UTC, braincodeishan commented on src/components/Product.jsx
> +          <Text weight={500}>{title.length>30?title.substring(0,29)+"...":title}</Text>
done

2023-07-14 05:19 UTC, braincodeishan commented
all changes requested are fulfilled.

2023-07-14 13:06 UTC, merged